steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/rent-room-api:v1.0.0", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/rent-room-api:v1.0.0"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "rent-room-service-be"
      - "--image=gcr.io/$PROJECT_ID/rent-room-api:v1.0.0"
      - "--region=asia-southeast2"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--env-vars-file=env.yaml"
      - "--port=8080"

images:
  - "gcr.io/$PROJECT_ID/rent-room-api:v1.0.0"
